package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Palettes
val LightPrimary = Color(0xFF3F51B5)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFE8EAF6)
val LightOnPrimaryContainer = Color(0xFF1A237E)
val LightSecondary = Color(0xFF5C6BC0)
val LightBackground = Color(0xFFF5F5FA)
val LightSurface = Color(0xFFFFFFFF)
val LightOnBackground = Color(0xFF1C1B1F)
val LightOnSurface = Color(0xFF1C1B1F)

// Vibrant Palette (Theme colors from Design HTML)
val VibrantPrimary = Color(0xFF0061A4)
val VibrantOnPrimary = Color(0xFFFFFFFF)
val VibrantPrimaryContainer = Color(0xFFD1E4FF)
val VibrantOnPrimaryContainer = Color(0xFF001D36)
val VibrantSecondary = Color(0xFF0061A4)
val VibrantBackground = Color(0xFFF7F9FF)
val VibrantSurface = Color(0xFFFFFFFF)
val VibrantOnBackground = Color(0xFF0F172A)
val VibrantOnSurface = Color(0xFF0F172A)
val VibrantSurfaceVariant = Color(0xFFF3F4F9)
val VibrantOnSurfaceVariant = Color(0xFF64748B)

// Dark Theme Palettes
val DarkPrimary = Color(0xFF9FA8DA)
val DarkOnPrimary = Color(0xFF1A237E)
val DarkPrimaryContainer = Color(0xFF283593)
val DarkOnPrimaryContainer = Color(0xFFE8EAF6)
val DarkSecondary = Color(0xFF7986CB)
val DarkBackground = Color(0xFF121218)
val DarkSurface = Color(0xFF1E1E24)
val DarkOnBackground = Color(0xFFE3E2E6)
val DarkOnSurface = Color(0xFFE3E2E6)

// Ice Theme Palettes (Frosty cool cyan and light gray)
val IcePrimary = Color(0xFF00ACC1)
val IceOnPrimary = Color(0xFFFFFFFF)
val IcePrimaryContainer = Color(0xFFE0F7FA)
val IceOnPrimaryContainer = Color(0xFF006064)
val IceSecondary = Color(0xFF0097A7)
val IceBackground = Color(0xFFF0F4F8)
val IceSurface = Color(0xFFFFFFFF)
val IceOnBackground = Color(0xFF102A43)
val IceOnSurface = Color(0xFF102A43)

// Lemon Theme Palettes (Vibrant citrus yellow and warm gray)
val LemonPrimary = Color(0xFFFBC02D)
val LemonOnPrimary = Color(0xFF212121)
val LemonPrimaryContainer = Color(0xFFFFFDE7)
val LemonOnPrimaryContainer = Color(0xFFF57F17)
val LemonSecondary = Color(0xFFFBC02D)
val LemonBackground = Color(0xFFFFFDF0)
val LemonSurface = Color(0xFFFFFFFF)
val LemonOnBackground = Color(0xFF212121)
val LemonOnSurface = Color(0xFF212121)

// Shirazi Theme Palettes (Soft rose pink and wine)
val ShiraziPrimary = Color(0xFFE91E63)
val ShiraziOnPrimary = Color(0xFFFFFFFF)
val ShiraziPrimaryContainer = Color(0xFFFCE4EC)
val ShiraziOnPrimaryContainer = Color(0xFF880E4F)
val ShiraziSecondary = Color(0xFFD81B60)
val ShiraziBackground = Color(0xFFFFF5F7)
val ShiraziSurface = Color(0xFFFFFFFF)
val ShiraziOnBackground = Color(0xFF2D101E)
val ShiraziOnSurface = Color(0xFF2D101E)

// Jungle Theme Palettes (Rich deep tropical greens)
val JunglePrimary = Color(0xFF2E7D32)
val JungleOnPrimary = Color(0xFFFFFFFF)
val JunglePrimaryContainer = Color(0xFFE8F5E9)
val JungleOnPrimaryContainer = Color(0xFF1B5E20)
val JungleSecondary = Color(0xFF4CAF50)
val JungleBackground = Color(0xFFF4F9F4)
val JungleSurface = Color(0xFFFFFFFF)
val JungleOnBackground = Color(0xFF0B250F)
val JungleOnSurface = Color(0xFF0B250F)

// Ocean Theme Palettes (Deep blue-green)
val OceanPrimary = Color(0xFF0288D1)
val OceanOnPrimary = Color(0xFFFFFFFF)
val OceanPrimaryContainer = Color(0xFFE1F5FE)
val OceanOnPrimaryContainer = Color(0xFF01579B)
val OceanSecondary = Color(0xFF00BCD4)
val OceanBackground = Color(0xFFF0F8FF)
val OceanSurface = Color(0xFFFFFFFF)
val OceanOnBackground = Color(0xFF002233)
val OceanOnSurface = Color(0xFF002233)

// Gold Theme Palettes (Luxury dark gold/bronze)
val GoldPrimary = Color(0xFFFFD700)
val GoldOnPrimary = Color(0xFF1A1A1A)
val GoldPrimaryContainer = Color(0xFF332B00)
val GoldOnPrimaryContainer = Color(0xFFFFE066)
val GoldSecondary = Color(0xFFB8860B)
val GoldBackground = Color(0xFF14130E)
val GoldSurface = Color(0xFF1F1D14)
val GoldOnBackground = Color(0xFFF5F2E6)
val GoldOnSurface = Color(0xFFF5F2E6)
